### ISSUE TITLE
File "movie_data_part2.csv" is missing in the repository

### ISSUE THREAD

**Issue by surtich** [Apress/applied-data-science-using-pyspark#1]

**Comment by Sundar0989** [comment]
Thanks for pointing it out. We just added the second dataset - "movie_data_part2_v1.csv.zip"

Due to GitHub limitation, we have updated the zipped file which has some records stripped from the complete dataset. Also changed the file name slightly ("movie_data_part2_v1.csv") from the original file name ("movie_data_part2.csv") used in the code. Please update accordingly, if you are using the reduced dataset. To access the complete dataset, please use the link - https://www.kaggle.com/kakarlaramcharan/tmdb-data-0920
